### ISSUE TITLE
Error in client - Could not find any resources appropriate for the specified culture or the neutral culture.

### ISSUE THREAD

**Issue by cdarrigo** [maartenba/WindowsAzure.Acs.Oauth2#10]
Steps to reproduce:
1) Create a new web app, add the WindowsAzure.Acs.Oauth2.Client package
2) Add the following to the home controller:

 public ActionResult Index()
        {
            var clientId = "dd4bb62f-d526-4236-9418-c76d027a1ecf";
            var clientSecret = "87ec9228-9dba-495c-bc69-2af226b5b258";
            var redirectUri = "http://localhost:7646/"; // client uri
            var scope = "http://localhost:7442/"; // defended resource realm
            var authServer = "http://localhost:7442/authorize";// uri to the authorize controller
            var apiRoot = "http://localhost:7442/"; // defended resoruce realm
            var accessTokenServer = "https://csdsample.accesscontrol.windows.net/v2/OAuth2-13/"; // OAuth2 endpoint in ACS (Created by ACS for us)

```
        var client = new SimpleOAuth2Client(new Uri(authServer), new Uri(accessTokenServer), clientId, clientSecret, scope, new Uri(redirectUri), ClientMode.TwoLegged);
        client.Authorize();

        var req = WebRequest.CreateHttp(apiRoot);
        client.AppendAccessTokenTo(req);

        var response = req.GetResponse();


        ViewBag.Title = "Home Page";

        return View();
    }
```

3) Run the site.  The following error is generated:

Server Error in '/' Application.

Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "WindowsAzure.Acs.Oauth2.Resources.resources" was correctly embedded or linked into assembly "WindowsAzure.Acs.Oauth2.Client" at compile time, or that all the satellite assemblies required are loadable and fully signed.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "WindowsAzure.Acs.Oauth2.Resources.resources" was correctly embedded or linked into assembly "WindowsAzure.Acs.Oauth2.Client" at compile time, or that all the satellite assemblies required are loadable and fully signed.

Source Error: 

Line 22: 
Line 23:             var client = new SimpleOAuth2Client(new Uri(authServer), new Uri(accessTokenServer), clientId, clientSecret, scope, new Uri(redirectUri), ClientMode.TwoLegged);
Line 24:             client.Authorize();

**Comment by maartenba** [comment]
Fixed and published to NuGet.org
