### ISSUE TITLE
Errors during startup.

### ISSUE THREAD

**Issue by cdarrigo** [maartenba/WindowsAzure.Acs.Oauth2#9]
I know this project is likely getting phased out, but I think it should still be functional with ACS.

After installing the pacakge, I have (so far) discovered two issues;
1) Wont compile due to missing AuthorizationServer reference. -  The AUthorizationController created extends AuthoirzationServer.  There is no class called AuthorizationServer.  In my code I manually changed this to ThreeLeggedAuthorizationServer.  I hope that is correct. 

2) During startup - I receive the following error:
Cannot register a module after the application has been initialized.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Cannot register a module after the application has been initialized.

Source Error: 

Line 17:             if (ConfigurationManager.AppSettings["WindowsAzure.OAuth.RelyingPartyRealm"] != null && ConfigurationManager.AppSettings["WindowsAzure.OAuth.ServiceNamespace"] != null && ConfigurationManager.AppSettings["WindowsAzure.OAuth.SwtSigningKey"] != null)
Line 18:             {
Line 19:                 Microsoft.Web.Infrastructure.DynamicModuleHelper.DynamicModuleUtility.RegisterModule(typeof(AcsAuthenticationModule));
Line 20:             }
Line 21:             else

Should I add this to the modules list in my web.config and comment this out?

**Comment by maartenba** [comment]
Will look into it and update the package on NuGet. Thanks for reporting!
